### ISSUE TITLE
Initial position on move animation

### ISSUE THREAD

**Issue by mecirmartin** [stefanwittwer/remotion-animated#2]
First of all thanks for this library, it's great tool to simplifying animations with remotion

As for my question: I don't understand, how the initial values of `Move` animation are supposed to work.
When i use `Move({ y: -100, initialY: 100 })` i would expect the element to be animated from bottom to the original position of this element (in my case in the center of wrapping div). Instead of this behavior, i see no change when using `initialY` or not
Am i doing something wrong?

Also i am curious if you plan to extend this library or if you would need some help with contributions, i would gladly help with development

**Comment by stefanwittwer** [comment]
Hi there! Thanks for trying out the library.

Yes, what you're expecting to happen is what is supposed to happen in theory😅
Could you share more of your example?

This library is mostly an extraction from some helper code I wrote to help me build an animation more quickly, as I noticed that it might be useful for others too (especially for chaining animations). Contributions are most welcome and are always very much appreciated!

**Comment by mecirmartin** [comment]
Sorry, already figured this one out, there was error on my side. Been working a lot lately 😅

Anyway, regarding the contributions: I would expect, that you have some roadmap or ideas for features that could be implemented. In that way i could contribute meaningfully. If you have something like that, feel free to reach out to me

I'm go ahead and close this one

**Comment by stefanwittwer** [comment]
Alright, glad to hear you figured out the issue! :)
I do have some plans on how to make the library more useful and extensible – I'll write them up when I have some time so you can have a look if it's something you'd like to contribute to.

Thanks again for using the library and for reaching out!
